//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uploading_and_retriving_Images.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web; ///this is for handling image posted 
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class Product
    {
        public int Id { get; set; }
        [DisplayName("Product Name")]
        [Required(ErrorMessage ="Product name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Product Price is required")]
        [DisplayName("Product Price")]

        public string Price { get; set; }
        [DisplayName("Choose Image")]
        public string Image_path { get; set; }
        public HttpPostedFileBase ImageFile { get; set; } //it requires System.web namespace
    }
}
