//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAppwithImages.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class employee
    {
        public int id { get; set; }
        [DisplayName("Employee Name")]
        [Required(ErrorMessage ="Employee Name is required")]
        public string name { get; set; }
        [DisplayName("Employee Designation")]
        [Required(ErrorMessage = "Employee Designation is required")]

        public string designation { get; set; }
        [DisplayName("Product")]

        public string image_path { get; set; } //this will store image path in db
        public HttpPostedFileBase ImageFile { get; set; }//through thisproperty only we will store our image in images folder 
    }
}
